// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CompleteTaskController from "./complete_task_controller"
application.register("complete-task", CompleteTaskController)

import RefreshUsersListController from "./refresh_users_list_controller"
application.register("refresh-users-list", RefreshUsersListController)

import KpiController from "./kpi_controller"
application.register("kpi", KpiController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)
